name = "Shourya Lala"
license = "BSD"
licenselink = "https://github.com/shouryalala/personal-page/blob/master/LICENSE"
description = "Personal page - Shourya Lala"
homepage = "https://shourya.io"
tags = ['shourya', 'lala', 'fast', 'light', 'modern', 'blog', 'technology', 'engineering', 'bootstrap', 'product', 'responsive', 'clean', 'simple', 'creative', 'aws', 'tutorials', 'mobile', 'minimalistic', 'library', 'ideas', 'portfolio', 'solutions', 'quick-read', 'presentation', 'product', 'typography']
features = ['bootstrap','responsive']
min_version = "0.1.0"

[author]
  name = "Shourya Lala"
  homepage = "https://shourya.io"
